import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Web3Providers from "@/lib/web3Provider";
import Header from "@/components/Header";
import "@rainbow-me/rainbowkit/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Caton",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-900 h-screen text-white">
          <Web3Providers>
            <Header />
            <div className="p-8 h-full max-w-3xl mx-auto shadow-lg">
              {children}
            </div>
          </Web3Providers>
        </div>
      </body>
    </html>
  );
}
